services:

 app:
    image: rest-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config.env
      ports:
      - "${APP_HOST}:8083"
    environment:
      - APP_ENV=local
      - APP_DSN=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=$DB_SSLMODE
    depends_on:
      - db
db:
  image: "postgres"
  restart: always
  env-file:
    - config.env
  environment:
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_DB: ${DB_NAME}
  ports:
    - "5432:${DB_PORT}"


      